spring:
  freemarker:
    #tpl模板文件的路径
    template-loader-path: classpath:/templates
    #关闭缓存，以便每次拿到最新的结果
    cache: false
    #tpl文件的编码格式
    charset: UTF-8
    #检查模板文件目录是否存在
    check-template-location: true
    content-type: text/html
    #设置所有request、session的属性在merger到模板的时候，是否都要添加到model中，一般web项目可能要设置为true
    expose-request-attributes: false
    expose-session-attributes: false
    #指定request context属性的名称
    request-context-attribute: request
    #设定模板的后缀
    suffix: .ftl
  thymeleaf:
    #模板文件路径
    prefix: classpath:/templates
    #模板文件后缀
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
